UPDATE doctor set speciality='C' WHERE speciality='Beautian';
UPDATE doctor set speciality='C' WHERE speciality='Beautician';
UPDATE doctor set speciality='CD' WHERE speciality='Cardiology';
UPDATE doctor set speciality='D' WHERE speciality='Dermatology';
UPDATE doctor set speciality='NTR' WHERE speciality='Dietitian';
UPDATE doctor set speciality='EM' WHERE speciality='Emergency';
UPDATE doctor set speciality='END' WHERE speciality='Endocrine';
UPDATE doctor set speciality='ENT' WHERE speciality='Ent';
UPDATE doctor set speciality='FP' WHERE speciality='Family';
UPDATE doctor set speciality='GE' WHERE speciality='Gastro';
UPDATE doctor set speciality='IM' WHERE speciality='Internal';
UPDATE doctor set speciality='NO CODE' WHERE speciality='Khafji';
UPDATE doctor set speciality='MKTG' WHERE speciality='Marketing';
UPDATE doctor set speciality='PUR' WHERE speciality='Neuro';
UPDATE doctor set speciality='N' WHERE speciality='Neurology';
UPDATE doctor set speciality='N' WHERE speciality='Nuerologist';
UPDATE doctor set speciality='NTR' WHERE speciality='Nutritionist';
UPDATE doctor set speciality='OBG' WHERE speciality='Ob-Gyne';
UPDATE doctor set speciality='NTR' WHERE speciality='Obesity Center';
UPDATE doctor set speciality='OBG' WHERE speciality='Obgyne';
UPDATE doctor set speciality='OPH' WHERE speciality='Opht';
UPDATE doctor set speciality='OPH' WHERE speciality='Opt';
UPDATE doctor set speciality='OPH' WHERE speciality='Opth';
UPDATE doctor set speciality='ORS' WHERE speciality='Ortho';
UPDATE doctor set speciality='PHM' WHERE speciality='Pharmacit';
UPDATE doctor set speciality='PHM' WHERE speciality='Pharmacy Manager';
UPDATE doctor set speciality='PS' WHERE speciality='Plastic Sergery';
UPDATE doctor set speciality='PS' WHERE speciality='Plastic Surgery';
UPDATE doctor set speciality='PUR' WHERE speciality='Purchasing';
UPDATE doctor set speciality='RHU' WHERE speciality='Rheumatic';
UPDATE doctor set speciality='RHU' WHERE speciality='Rheumatoid';
